version: '3.8'

services:
  web:
    image: 474668398195.dkr.ecr.us-east-1.amazonaws.com/chatgenius:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@db:5432/chatgenius
    depends_on:
      - db
    command: sh -c "npm run db:migrate && npm run start"
    logging:
      driver: awslogs
      options:
        awslogs-group: chatgenius
        awslogs-region: us-east-1
        awslogs-stream-prefix: web

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chatgenius
    volumes:
      - /ecs/postgres-data:/var/lib/postgresql/data
    logging:
      driver: awslogs
      options:
        awslogs-group: chatgenius
        awslogs-region: us-east-1
        awslogs-stream-prefix: db

volumes:
  postgres-data:
    driver: local 