FROM node:20-alpine

WORKDIR /app

# Copy package files and env
COPY package*.json .env ./

# Install dependencies
RUN npm ci

# Copy application files
COPY . .

# Run migrations and generate types
CMD sh -c "npm run db:migrate && npm run db:generate" 